name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: v1.0.0
   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cr.yandex/crpjresmdt6bvu99mm57/my_app:${{ steps.previoustag.outputs.tag }}-${{ steps.previoustag.outputs.timestamp }} 
      # --tag cr.yandex/crpjresmdt6bvu99mm57/my_app:latest

    - name: Docker list image
      run: docker image ls
      
    - name: Docker login
      run: docker login --username oauth --password ${{ secrets.YC_SERVICE_ACCOUNT }}  cr.yandex

    - name: Publish image
      run: docker push cr.yandex/crpjresmdt6bvu99mm57/my_app:${{ steps.previoustag.outputs.tag }}-${{ steps.previoustag.outputs.timestamp }} 
        # docker push cr.yandex/crpjresmdt6bvu99mm57/my_app:latest
