name: Deploy Docker Image CI

on:
  push:
    tags: 
      - v*.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cr.yandex/crpjresmdt6bvu99mm57/my_app:$GITHUB_REF_NAME --tag cr.yandex/crpjresmdt6bvu99mm57/my_app:latest
      
    - name: Docker login
      run: docker login --username oauth --password ${{ secrets.YC_SERVICE_ACCOUNT }}  cr.yandex

    - name: Publish image
      run: | 
        docker push cr.yandex/crpjresmdt6bvu99mm57/my_app:$GITHUB_REF_NAME 
        docker push cr.yandex/crpjresmdt6bvu99mm57/my_app:latest

    - name: Deploy
      if: startsWith(github.ref, 'refs/tags/v')    
      run: |
        git clone git@github.com:splunk/qbec
        cd qbec
        make install  
        make
        qbec apply default

      # if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'

