name: Deploy Docker Image CI

on:
  push:
    tags: 
      - v*.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cr.yandex/crpjresmdt6bvu99mm57/my_app:${GITHUB_REF##*/} --tag cr.yandex/crpjresmdt6bvu99mm57/my_app:latest
      
    - name: Docker login
      run: docker login --username oauth --password ${{ secrets.YC_SERVICE_ACCOUNT }}  cr.yandex

    - name: Publish image
      run: | 
        docker push cr.yandex/crpjresmdt6bvu99mm57/my_app:${GITHUB_REF##*/} 
        docker push cr.yandex/crpjresmdt6bvu99mm57/my_app:latest

    - name: Deploy
      if: startsWith(github.ref, 'refs/tags/v')    
      run: |
        apt install go
        apt install golang
        git clone https://github.com/splunk/qbec.git
        cd qbec
        make install  
        make
        qbec apply default

      # if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
# jobs:
#   container-test-job:
#     runs-on: ubuntu-latest
#     container:
#       image: node:18
#       env:
#         NODE_ENV: development
#       ports:
#         - 80
#       volumes:
#         - my_docker_volume:/volume_mount
#       options: --cpus 1
#     steps:
#       - name: Check for dockerenv file
#         run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
